@startuml
title Diagrama de Despliegue - Sistema de Matrícula Universitaria

node "Dispositivo del Usuario" {

node "PC / Laptop" {

artifact "Navegador Web\nChrome / Edge / Firefox"

}

}

cloud Internet

node "Servidor Web" {

artifact "Aplicación Web"

}

node "Servidor de Aplicaciones" {

artifact "Lógica de Negocio"

}

database "Servidor de Base de Datos" {

database "SQL Server / MySQL"

}

"PC / Laptop" --> Internet
Internet --> "Servidor Web"

"Servidor Web" --> "Servidor de Aplicaciones"

"Servidor de Aplicaciones" --> "Servidor de Base de Datos"

@enduml