@startuml
title Actividad - Matrícula de Cursos

start

:Iniciar sesión;

:Consultar oferta de cursos;

:Seleccionar cursos;

if (¿Cumple prerrequisitos?) then (Sí)

    if (¿Hay cupos?) then (Sí)

        if (¿Existe choque de horario?) then (No)

            :Registrar matrícula;

            :Actualizar horario;

            :Mostrar confirmación;

        else (Sí)

            :Mostrar error de horario;

        endif

    else (No)

        :Mostrar grupo lleno;

    endif

else (No)

:Mostrar que no cumple prerrequisitos;

endif

stop

@enduml